name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: .NET Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore
        
  test:
    name: .Net Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: WebApi
            project: EndpointForge.WebApi.Tests/EndpointForge.WebApi.Tests.csproj
          - name: Integration
            project: EndpointForge.IntegrationTests/EndpointForge.IntegrationTests.csproj

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore Dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build solution
        run: dotnet build  ${{ matrix.project }} --configuration Release --no-restore

      - name: Setup Dev Credentials
        run: dotnet dev-certs https --trust
        if: ${{ matrix.name == 'Integration' }}
          
      - name: Run tests
        run: dotnet test  ${{ matrix.project }} --configuration Release --no-build --verbosity normal